"""Add Bio and Profile Column

Revision ID: 79311f04ace8
Revises: 637115974daf
Create Date: 2021-02-25 12:30:23.827780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79311f04ace8'
down_revision = '637115974daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
